[package]
name = "project"
version = "0.1.0"
edition = "2021"

[dependencies]
sys-info = "0.9.1"
criterion = "0.5.1"
rayon = "1.7"
fs_extra = "1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

